export interface MomentQuestion {
  path: 1 | 2 | 3;
  index: number;
  text: string;
  example?: string | null;
}

export const MOMENT_QUESTIONS: MomentQuestion[] = [
  // Path 1: Light & Fun (35)
  { path: 1, index: 0, text: "What's your favorite way to spend a lazy Sunday?", example: 'Reading in bed, watching a movie, or going for a walk?' },
  { path: 1, index: 1, text: "What food always reminds you of happy memories?" },
  { path: 1, index: 2, text: "What's one place you've always wanted to visit together?" },
  { path: 1, index: 3, text: "What's your favorite memory from when we first met?" },
  { path: 1, index: 4, text: "If you could have any superpower for a day, what would it be?" },
  { path: 1, index: 5, text: "What's your favorite way to relax after a long day?", example: 'Hot bath, music, or quiet time together?' },
  { path: 1, index: 6, text: "What song always puts you in a good mood?" },
  { path: 1, index: 7, text: "What's one thing you loved doing as a child?" },
  { path: 1, index: 8, text: "What's your favorite comfort food?" },
  { path: 1, index: 9, text: "What's one thing that always makes you feel excited?" },
  { path: 1, index: 10, text: "What's your favorite way to start the day?", example: 'Coffee in bed, a hug, or watching the sunrise?' },
  { path: 1, index: 11, text: "What's one thing you're grateful for right now?" },
  { path: 1, index: 12, text: "What's your favorite way we make each other laugh?" },
  { path: 1, index: 13, text: "What's one thing you love about our home?" },
  { path: 1, index: 14, text: "What's your favorite way to unwind together?" },
  { path: 1, index: 15, text: "What's one thing that always makes you feel loved?" },
  { path: 1, index: 16, text: "What's your favorite season and why?" },
  { path: 1, index: 17, text: "What's one thing you're looking forward to this month?" },
  { path: 1, index: 18, text: "What's your favorite way to celebrate small wins?", example: 'A treat, a dance, or telling each other?' },
  { path: 1, index: 19, text: "What's one thing that always makes you feel proud of yourself?" },
  { path: 1, index: 20, text: "What's your favorite way we show love to each other?", example: 'Words, touch, or acts of service?' },
  { path: 1, index: 21, text: "What's one thing you loved about our last date?" },
  { path: 1, index: 22, text: "What's one thing that always makes you feel cared for?" },
  { path: 1, index: 23, text: "What's one thing you're really good at?" },
  { path: 1, index: 24, text: "What's your favorite way we spend time together?", example: 'Cooking, walks, or quiet nights in?' },
  { path: 1, index: 25, text: "What's one thing that always brightens your day?" },
  { path: 1, index: 26, text: "What's one thing you've always wanted to try but haven't yet?" },
  { path: 1, index: 27, text: "What's your favorite way I make you laugh?" },
  { path: 1, index: 28, text: "What's one thing that always makes you smile?" },
  { path: 1, index: 29, text: "If you could live to 90 and keep either the mind or body of a 30-year-old, which would you choose?" },
  { path: 1, index: 30, text: "What's one thing you're grateful for in our relationship right now?" },
  { path: 1, index: 31, text: "What's one thing that always makes you feel excited about us?" },
  { path: 1, index: 32, text: "What's your favorite way to start the day together?" },
  { path: 1, index: 33, text: "What's one thing you love about our home?", example: 'A corner, a ritual, or the feeling?' },
  { path: 1, index: 34, text: "What's one small thing we could do this week to add more joy?" },
  // Path 2: Deeper Connection (35)
  { path: 2, index: 0, text: "What's one thing that made you feel really seen this week?" },
  { path: 2, index: 1, text: "What's a memory that still makes you feel emotional?" },
  { path: 2, index: 2, text: "What's one fear you have about the future?" },
  { path: 2, index: 3, text: "What's something you've never told me before that you want to share?" },
  { path: 2, index: 4, text: "What's one way I make you feel safe?" },
  { path: 2, index: 5, text: "What's a moment when you felt really proud of us?" },
  { path: 2, index: 6, text: "What's one thing you wish I understood better about you?" },
  { path: 2, index: 7, text: "What's a hard thing you've been carrying lately?" },
  { path: 2, index: 8, text: "What's one way our relationship has changed you for the better?" },
  { path: 2, index: 9, text: "What's a dream you have that you haven't told me about?" },
  { path: 2, index: 10, text: "What's one thing that always makes you feel loved by me?" },
  { path: 2, index: 11, text: "What's a time when you felt really supported by me?" },
  { path: 2, index: 12, text: "What's one thing you're learning about love right now?" },
  { path: 2, index: 13, text: "What's a moment when you felt really close to me?" },
  { path: 2, index: 14, text: "What's one thing you wish we did more of together?" },
  { path: 2, index: 15, text: "What's a fear you've overcome in our relationship?" },
  { path: 2, index: 16, text: "What's one way I make you feel cherished?" },
  { path: 2, index: 17, text: "What's a memory that still makes you feel grateful?" },
  { path: 2, index: 18, text: "What's one thing you want me to know about your heart?" },
  { path: 2, index: 19, text: "What's a moment when you felt really understood by me?" },
  { path: 2, index: 20, text: "What's one way we can support each other better?" },
  { path: 2, index: 21, text: "What's one thing you need from me when you're stressed?" },
  { path: 2, index: 22, text: "What's a hope you have for us that you haven't said out loud?" },
  { path: 2, index: 23, text: "What's one way I could show up for you more?" },
  { path: 2, index: 24, text: "What's something you're afraid to ask for in our relationship?" },
  { path: 2, index: 25, text: "What's one way we've grown together that you're proud of?" },
  { path: 2, index: 26, text: "What's a moment when you felt really chosen by me?" },
  { path: 2, index: 27, text: "What's one thing you're still healing from that affects us?" },
  { path: 2, index: 28, text: "What's one way we can be more honest with each other?" },
  { path: 2, index: 29, text: "What's something you need to hear from me more often?" },
  { path: 2, index: 30, text: "What's one boundary you'd like us to respect more?" },
  { path: 2, index: 31, text: "What's a time when you felt disconnected and what helped?" },
  { path: 2, index: 32, text: "What's one thing you're scared to try in our relationship?" },
  { path: 2, index: 33, text: "What's one way we can make conflict bring us closer?" },
  { path: 2, index: 34, text: "What's one thing you want to forgive or let go of together?" },
  // Path 3: Future & Legacy (30)
  { path: 3, index: 0, text: "What's one dream you have for our life together in 5 years?" },
  { path: 3, index: 1, text: "What kind of legacy do you want to leave together?" },
  { path: 3, index: 2, text: "What's one tradition you'd love to start with me?" },
  { path: 3, index: 3, text: "What's a hope you have for our future family (or life)?" },
  { path: 3, index: 4, text: "What's one way we can support each other's dreams better?" },
  { path: 3, index: 5, text: "What's a moment you hope we'll always remember?" },
  { path: 3, index: 6, text: "What's one thing you want us to keep doing forever?" },
  { path: 3, index: 7, text: "What's a promise you want to keep for us?" },
  { path: 3, index: 8, text: "What's one way we can grow closer in the coming year?" },
  { path: 3, index: 9, text: "What's a value you want to pass on together?" },
  { path: 3, index: 10, text: "What's one adventure you want us to have?" },
  { path: 3, index: 11, text: "What's one way we can make our love stronger over time?" },
  { path: 3, index: 12, text: "What's a dream you have for our life beyond the everyday?" },
  { path: 3, index: 13, text: "What's one thing you want us to keep choosing every day?" },
  { path: 3, index: 14, text: "What's one way we can make our home feel more like a sanctuary?" },
  { path: 3, index: 15, text: "What's a goal you have for our relationship in the next year?" },
  { path: 3, index: 16, text: "What's one thing you want to learn together?" },
  { path: 3, index: 17, text: "What's a place you want to go with me one day?" },
  { path: 3, index: 18, text: "What's one way we can leave the world better together?" },
  { path: 3, index: 19, text: "What's a story you want to tell about us in 20 years?" },
  { path: 3, index: 20, text: "What's one ritual you'd want to do with me for the rest of our lives?" },
  { path: 3, index: 21, text: "What's one thing you want our future kids (or people we influence) to learn from us?" },
  { path: 3, index: 22, text: "What's one way we can invest in our relationship this year?" },
  { path: 3, index: 23, text: "What's a dream trip or experience we should plan for?" },
  { path: 3, index: 24, text: "What's one thing you want to build or create with me?" },
  { path: 3, index: 25, text: "What's one way we can stay curious about each other as we change?" },
  { path: 3, index: 26, text: "What's one promise to yourself you want me to help you keep?" },
  { path: 3, index: 27, text: "What's one way we can celebrate our relationship more?" },
  { path: 3, index: 28, text: "What's one thing you want to be true of us when we're old?" },
  { path: 3, index: 29, text: "What's one hope you have for the next chapter of our story?" },
];

export function getQuestionsByPath(path: 1 | 2 | 3): MomentQuestion[] {
  return MOMENT_QUESTIONS.filter(q => q.path === path);
}

export const PATH_LABELS: Record<1 | 2 | 3, string> = {
  1: 'Light & Fun',
  2: 'Deeper Connection',
  3: 'Future & Legacy',
};

export const PATH_COUNTS: Record<1 | 2 | 3, number> = {
  1: 35,
  2: 35,
  3: 30,
};
